/*
A KBase module: kb_ke_apps
*/

module kb_ke_apps {

  /* A boolean - 0 for false, 1 for true.
    @range (0, 1)
  */
  typedef int boolean;

  /* An X/Y/Z style reference*/
  typedef string obj_ref;

  /* Input of the run_expression_matrix_cluster function
    matrix_ref: Matrix object reference
    workspace_name: the name of the workspace
    feature_set_suffix: suffix append to FeatureSet object name
    dist_threshold: the threshold to apply when forming flat clusters

    Optional arguments:
    dist_metric: The distance metric to use. Default set to 'euclidean'.
                 The distance function can be
                 ["braycurtis", "canberra", "chebyshev", "cityblock", "correlation", "cosine", 
                  "dice", "euclidean", "hamming", "jaccard", "kulsinski", "matching", 
                  "rogerstanimoto", "russellrao", "sokalmichener", "sokalsneath", "sqeuclidean", 
                  "yule"]
                 Details refer to:
                 https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html

    linkage_method: The linkage algorithm to use. Default set to 'ward'.
                    The method can be
                    ["single", "complete", "average", "weighted", "centroid", "median", "ward"]
                    Details refer to:
                    https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html

    fcluster_criterion: The criterion to use in forming flat clusters. Default set to 'distance'.
                        The criterion can be
                        ["inconsistent", "distance", "maxclust"]
                        Details refer to:
                        https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.fcluster.html
  */
  typedef structure {
    obj_ref matrix_ref;
    string workspace_name;
    string feature_set_suffix;
    float dist_threshold;

    string dist_metric;
    string linkage_method;
    string fcluster_criterion;
  } EMClusterParams;

  /* Ouput of the run_expression_matrix_cluster function
    feature_set_set_refs: a list of result FeatureSetSet object references
    report_name: report name generated by KBaseReport
    report_ref: report reference generated by KBaseReport
  */
  typedef structure {
    list<obj_ref> feature_set_set_refs;
    string report_name;
    string report_ref;
  } EMClusterOutput;

  /* run_expression_matrix_cluster: generates clusters for ExpressionMatrix data object*/
  funcdef run_expression_matrix_cluster(EMClusterParams params) returns(EMClusterOutput returnVal) authentication required;

};
